// Authentication Routes
export const AuthRoutes = {
  LOGIN: "/login",
  ADMIN_LOGIN: "/admin/login",
  REGISTER: "/register",
};

// Authenticated Routes
export const AuthenticatedRoutes = {
  USER_HOME: "/",
  USER_DASHBOARD: "/dashboard",
  USER_PROFILE: "/profile",
  BANK_DETAILS: "/bank-details",
  PACKAGE_REPORT: "/package-report",
  SELF_INCOME_REPORT: "/self-income-report",
  REFERRAL_INCOME_REPORT: "/referral-income-report",
  SPIN_INCOME_REPORT: "/spin-income-report",
  LEVEL_INCOME_REPORT: "/level-income-report",
  MATCHING_INCOME_REPORT: "/matching-income-report",
  ROYALTY_INCOME_REPORT: "/royalty-income-report",
  FUND_TRANSFER: "/fund-transfer",
  FUND_REQUEST: "/fund-request",
  FUND_REQUEST_HISTORY: "/fund-request-history",
  FUND_TRANSFER_HISTORY: "/fund-transfer-history",
  FUND_RECEIVE_HISTORY: "/fund-receive-history",
  ALL_WITHDRAWAL_HISTORY: "/all-withdrawal-history",
  ALL_INCOME_HISTORY : "/all-income-history",
  TEAM_DIRECT: "/team-direct",
  TEAM_TREE: "/team-tree",
  WALLET : "/wallet",
  WITHDRAWAL_REQUEST :"/withdrawal-request",
  WITHDRAWAL_REPORT: "/withdrawal-report",
  OUR_PLANS: "/our-plans",
  OUR_PLANS_ADMIN: "/our-plans-admin",
  ADD_PLANS: "/add-plans",
  Empty_ROUTE: "/empty-route",
  UPDATE_LOAN_STATUS :"/update-loan-status",
  LOAN_STATUS :"/loan-status",
  ADMIN_DASHBOARD: "/admin-dashboard",
  LOAN_FORM : "/loan-request-form",
  PENDING_USERS: "/pending-users",
  PENDING_FUND_REQUEST: "/pending-fund-request",
  PENDING_WITHDRAWAL_REQUEST: "/pending-withdrawal-request",
  APPROVED_USERS: "/approved-users",
  APPROVED_FUND_REQUEST: "/approved-fund-request",
  APPROVED_WITHDRAWAL_REQUEST: "/approved-withdrawal-request",
  PLAN_HISTORY: "/plans-history",
  REJECTED_FUND_REQUEST: "/rejected-fund-request",
  REJECTED_WITHDRAWAL_REQUEST: "/rejected-withdrawal-request",
  SUPPORT_RAISE_TICKET_HISTORY: "/support-raise-ticket-history",
  CONTACT_US: "/contact-us",
  RAISE_TICKET_LIST: "/raise-ticket-list",
  ALL_USERS: "/all-users",
  All_Investment_History : "/investment-history"
};
